package com.example.konradpodogrski_nbp

import java.io.Serializable

public class Countries{
    companion object {
        val codeToCountry: Map<String, String> = mapOf(
            "AED" to "United Arab Emirates",
            "AFN" to "Afghanistan",
            "ALL" to "Albania",
            "AMD" to "Armenia",
            "ANG" to "Netherlands Antilles",
            "AOA" to "Angola",
            "ARS" to "Argentina",
            "AUD" to "Australia",
            "AWG" to "Aruba",
            "AZN" to "Azerbaijan",
            "BAM" to "Bosnia and Herzegovina",
            "BBD" to "Barbados",
            "BDT" to "Bangladesh",
            "BGN" to "Bulgaria",
            "BHD" to "Bahrain",
            "BIF" to "Burundi",
            "BMD" to "Bermuda",
            "BND" to "Brunei",
            "BOB" to "Bolivia",
            "BOV" to "Bolivia",
            "BRL" to "Brazil",
            "BSD" to "Bahamas",
            "BTN" to "Bhutan",
            "BWP" to "Botswana",
            "BYR" to "Belarus",
            "BZD" to "Belize",
            "CAD" to "Canada",
            "CDF" to "Democratic Republic of Congo",
            "CHE" to "Switzerland",
            "CHF" to "Switzerland",
            "CHW" to "Switzerland",
            "CLF" to "Chile",
            "CLP" to "Chile",
            "CNY" to "China",
            "COP" to "Colombia",
            "COU" to "Colombia",
            "CRC" to "Costa Rica",
            "CUP" to "Cuba",
            "CVE" to "Cape Verde",
            "CYP" to "Cyprus",
            "CZK" to "Czechia",
            "DJF" to "Djibouti",
            "DKK" to "Denmark",
            "DOP" to "Dominican Republic",
            "DZD" to "Algeria",
            "EEK" to "Estonia",
            "EGP" to "Egypt",
            "ERN" to "Eritrea",
            "ETB" to "Ethiopia",
            "EUR" to "European Union",
            "FJD" to "Fiji",
            "FKP" to "Falkland Islands",
            "GBP" to "United Kingdom",
            "GEL" to "Georgia",
            "GHS" to "Ghana",
            "GIP" to "Gibraltar",
            "GMD" to "Gambia",
            "GNF" to "Guinea",
            "GTQ" to "Guatemala",
            "GYD" to "Guyana",
            "HKD" to "China",
            "HNL" to "Honduras",
            "HRK" to "Croatia",
            "HTG" to "Haiti",
            "HUF" to "Hungary",
            "IDR" to "Indonesia",
            "ILS" to "Israel",
            "INR" to "India",
            "IQD" to "Iraq",
            "IRR" to "Iran",
            "ISK" to "Iceland",
            "JMD" to "Jamaica",
            "JOD" to "Jordan",
            "JPY" to "Japan",
            "KES" to "Kenya",
            "KGS" to "Kyrgyzstan",
            "KHR" to "Cambodia",
            "KMF" to "Comoros",
            "KPW" to "North Korea",
            "KWD" to "Kuwait",
            "KRW" to "South Korea",
            "KYD" to "Cayman Islands",
            "KZT" to "Kazakhstan",
            "LAK" to "Laos",
            "LBP" to "Lebanon",
            "LKR" to "Sri Lanka",
            "LRD" to "Liberia",
            "LSL" to "Lesotho",
            "LTL" to "Lithuania",
            "LVL" to "Latvia",
            "LYD" to "Libya",
            "MAD" to "Morocco, Western Sahara",
            "MDL" to "Moldova",
            "MGA" to "Madagascar",
            "MKD" to "Former Yugoslav Republic of Macedonia",
            "MMK" to "Myanmar",
            "MNT" to "Mongolia",
            "MOP" to "Macau Special Administrative Region",
            "MRO" to "Mauritania",
            "MTL" to "Malta",
            "MUR" to "Mauritius",
            "MVR" to "Maldives",
            "MWK" to "Malawi",
            "MXN" to "Mexico",
            "MXV" to "Mexico",
            "MYR" to "Malaysia",
            "MZN" to "Mozambique",
            "NAD" to "Namibia",
            "NGN" to "Nigeria",
            "NIO" to "Nicaragua",
            "NOK" to "Norway",
            "NPR" to "Nepal",
            "NZD" to "New Zealand",
            "OMR" to "Oman",
            "PAB" to "Panama",
            "PEN" to "Peru",
            "PGK" to "Papua New Guinea",
            "PHP" to "Philippines",
            "PKR" to "Pakistan",
            "PLN" to "Poland",
            "PYG" to "Paraguay",
            "QAR" to "Qatar",
            "RON" to "Romania",
            "RSD" to "Serbia",
            "RUB" to "Russia",
            "RWF" to "Rwanda",
            "SAR" to "Saudi Arabia",
            "SBD" to "Solomon Islands",
            "SCR" to "Seychelles",
            "SDG" to "Sudan",
            "SEK" to "Sweden",
            "SGD" to "Singapore",
            "SHP" to "Saint Helena",
            "SKK" to "Slovakia",
            "SLL" to "Sierra Leone",
            "SOS" to "Somalia",
            "SRD" to "Suriname",
            "STD" to "São Tomé and Príncipe",
            "SYP" to "Syria",
            "SZL" to "Swaziland",
            "THB" to "Thailand",
            "TJS" to "Tajikistan",
            "TMM" to "Turkmenistan",
            "TND" to "Tunisia",
            "TOP" to "Tonga",
            "TRY" to "Turkey",
            "TTD" to "Trinidad and Tobago",
            "TWD" to "Taiwan and other islands that are under the effective control of the Republic of China (ROC)",
            "TZS" to "Tanzania",
            "UAH" to "Ukraine",
            "UGX" to "Uganda",
            "USD" to "USA",
            "USN" to "United States",
            "USS" to "United States",
            "UYU" to "Uruguay",
            "UZS" to "Uzbekistan",
            "VEB" to "Venezuela",
            "VND" to "Vietnam",
            "VUV" to "Vanuatu",
            "WST" to "Samoa",
            "XAF" to "Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon",
            "XAG" to "",
            "XAU" to "",
            "XBA" to "",
            "XBB" to "",
            "XBC" to "",
            "XBD" to "",
            "XCD" to "Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines",
            "XDR" to "InternationalMonetaryFund",
            "XFO" to "Bank for International Settlements",
            "XFU" to "International Union of Railways",
            "XOF" to "Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo",
            "XPD" to "",
            "XPF" to "French Polynesia, New Caledonia, Wallis and Futuna",
            "XPT" to "",
            "XTS" to "",
            "XXX" to "",
            "YER" to "Yemen",
            "ZAR" to "South Africa",
            "ZMK" to "Zambia",
            "ZWD" to "Zimbabwe");
    }
}